### ISSUE TITLE
Issue with # 

### ISSUE THREAD

**Issue by TomaszKot11** [MarkKhramko/nodejs-express-jwt#3]
Requires are wrongly defined with # ?

**Comment by MarkKhramko** [comment]
> Requires are wrongly defined with # ?

Hi Tomasz! `#` in requires is basically a shortcut for folder. So instead of `../../../app/models/User` we simply write `#models/User`. It is parsed by `babel-plugin-module-resolver` (can be found in package.json/devDependencies). 
Config for those shortcuts can be found inside `.babelrc` file inside project root directory. Feel free to edit it how you like 😉.
